//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int member_id { get; set; }
        public string member_usr { get; set; }
        public string member_pass { get; set; }
        public Nullable<int> member_age { get; set; }
    }
}
